# This is an algorithm to convert a 5-point likert based scale to a continuess Guassian fuzzy number.

In [1]:
#First one must import the necessary data analysis librarires

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random as rnd
#Warnings might become somewhat troublesome so the next import is for convinience.
import warnings
warnings.filterwarnings("ignore")

In [2]:
#reading the raw data first.
raw_data=pd.read_csv('Fuzzification.csv')

In [3]:
#trimming the unnecessary data away

raw_data.drop(columns='idcode',inplace=True)

In [4]:
raw_data.drop(columns=['SMU','SM','PK1','PK2','PK3','Age'],inplace=True)

In [5]:
#defining the dictionnaries for TFNS
low_bound={1:0.000,2:0.000,3:0.250,4:0.500,5:0.750}
mid_bound={1:0.000,2:0.250,3:0.500,4:0.750,5:1.000}
up_bound={1:0.250,2:0.500,3:0.750,4:1.000,5:1.000}

#defining the CoG dictionary

CoG={1:((low_bound[1]+4*mid_bound[1]+up_bound[1])/6),
     2:((low_bound[2]+4*mid_bound[2]+up_bound[2])/6),
     3:((low_bound[3]+4*mid_bound[3]+up_bound[3])/6),
     4:((low_bound[4]+4*mid_bound[4]+up_bound[4])/6),
     5:((low_bound[5]+4*mid_bound[5]+up_bound[5])/6)}

In [6]:
raw_data_CoG=raw_data.copy()
for col in raw_data_CoG.columns:
    raw_data_CoG[col]=raw_data_CoG[col].map(CoG)
raw_data_CoG

,ENT1,ENT2,ENT3,ENT4,INT1,INT2,INT3,CUS1,CUS2,CUS3,...,RB2,RB3,RB4,RB5,RB6,VI1,VI2,VI3,VI4,VI5
0,0.750000,0.750000,0.750000,0.958333,0.958333,0.750000,0.750000,0.250000,0.500000,0.750000,...,0.958333,0.958333,0.958333,0.958333,0.750000,0.750000,0.500000,0.500000,0.500000,0.750000
1,0.750000,0.750000,0.750000,0.750000,0.750000,0.750000,0.750000,0.750000,0.500000,0.750000,...,0.750000,0.750000,0.750000,0.750000,0.750000,0.750000,0.750000,0.750000,0.750000,0.750000
2,0.958333,0.958333,0.958333,0.958333,0.958333,0.958333,0.750000,0.958333,0.958333,0.958333,...,0.958333,0.958333,0.958333,0.958333,0.500000,0.958333,0.958333,0.958333,0.958333,0.958333
3,0.958333,0.958333,0.958333,0.958333,0.958333,0.750000,0.750000,0.958333,0.958333,0.750000,...,0.958333,0.958333,0.958333,0.958333,0.958333,0.750000,0.750000,0.958333,0.750000,0.750000
4,0.750000,0.958333,0.750000,0.958333,0.750000,0.750000,0.750000,0.750000,0.750000,0.750000,...,0.750000,0.958333,0.750000,0.958333,0.750000,0.750000,0.750000,0.750000,0.958333,0.750000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,0.750000,0.958333,0.750000,0.958333,0.958333,0.750000,0.750000,0.500000,0.750000,0.500000,...,0.750000,0.750000,0.958333,0.750000,0.958333,0.958333,0.958333,0.958333,0.958333,0.958333
302,0.750000,0.750000,0.750000,0.958333,0.958333,0.958333,0.750000,0.958333,0.750000,0.750000,...,0.750000,0.958333,0.958333,0.750000,0.958333,0.958333,0.958333,0.500000,0.958333,0.958333
303,0.958333,0.750000,0.750000,0.958333,0.958333,0.750000,0.750000,0.750000,0.958333,0.958333,...,0.750000,0.750000,0.750000,0.958333,0.958333,0.958333,0.750000,0.750000,0.750000,0.958333
304,0.750000,0.958333,0.750000,0.750000,0.750000,0.750000,0.958333,0.750000,0.958333,0.750000,...,0.750000,0.958333,0.750000,0.750000,0.958333,0.750000,0.750000,0.750000,0.750000,0.958333
305,0.750000,0.750000,0.958333,0.750000,0.750000,0.958333,0.958333,0.750000,0.958333,0.500000,...,0.958333,0.750000,0.958333,0.958333,0.750000,0.958333,0.750000,0.750000,0.750000,0.958333

In [7]:
import random
Mu={1:0.021,2:0.146,3:0.375,4:0.625,5:0.979}
std={1:0.021,2:0.104,3:0.125,4:0.125,5:0.021}

#defining the random dictionary 
rnd={1:random.normalvariate(Mu[1], std[1]),
    2:random.normalvariate(Mu[2], std[2]),
    3:random.normalvariate(Mu[3], std[3]),
    4:random.normalvariate(Mu[4], std[4]),
    5:random.normalvariate(Mu[5], std[5])}

raw_data_rnd=raw_data.copy()

for col in raw_data_rnd.columns:
    raw_data_rnd[col]=raw_data_rnd[col].apply(lambda x: random.normalvariate(Mu[x], std[x]) if x in Mu else x)
raw_data_rnd

,ENT1,ENT2,ENT3,ENT4,INT1,INT2,INT3,CUS1,CUS2,CUS3,...,RB2,RB3,RB4,RB5,RB6,VI1,VI2,VI3,VI4,VI5
0,0.553770,0.553260,0.563023,0.979681,1.055670,0.309395,0.707088,0.155316,0.243684,0.683215,...,0.981952,0.999776,0.987742,0.995295,0.461379,0.381469,0.325452,0.442920,0.454944,0.464899
1,0.553770,0.553260,0.563023,0.682271,0.639446,0.309395,0.707088,0.796671,0.243684,0.683215,...,0.602601,0.743449,0.596581,0.664205,0.461379,0.381469,0.575789,0.673260,0.801421,0.464899
2,1.015657,0.990266,0.983659,0.979681,1.055670,0.967586,0.707088,1.001008,0.962434,0.992294,...,0.981952,0.999776,0.987742,0.995295,0.343490,0.977762,0.950374,0.999934,0.969314,0.999446
3,1.015657,0.990266,0.983659,0.979681,1.055670,0.309395,0.707088,1.001008,0.962434,0.683215,...,0.981952,0.999776,0.987742,0.995295,1.004012,0.381469,0.575789,0.999934,0.801421,0.464899
4,0.553770,0.990266,0.563023,0.979681,0.639446,0.309395,0.707088,0.796671,0.833847,0.683215,...,0.602601,0.999776,0.596581,0.995295,0.461379,0.381469,0.575789,0.673260,0.969314,0.464899
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,0.553770,0.990266,0.563023,0.979681,1.055670,0.309395,0.707088,0.286599,0.833847,0.509108,...,0.602601,0.743449,0.987742,0.664205,1.004012,0.977762,0.950374,0.999934,0.969314,0.999446
302,0.553770,0.553260,0.563023,0.979681,1.055670,0.967586,0.707088,1.001008,0.833847,0.683215,...,0.602601,0.999776,0.987742,0.664205,1.004012,0.977762,0.950374,0.442920,0.969314,0.999446
303,1.015657,0.553260,0.563023,0.979681,1.055670,0.309395,0.707088,0.796671,0.962434,0.992294,...,0.602601,0.743449,0.596581,0.995295,1.004012,0.977762,0.575789,0.673260,0.801421,0.999446
304,0.553770,0.990266,0.563023,0.682271,0.639446,0.309395,0.971169,0.796671,0.962434,0.683215,...,0.602601,0.999776,0.596581,0.664205,1.004012,0.381469,0.575789,0.673260,0.801421,0.999446
305,0.553770,0.553260,0.983659,0.682271,0.639446,0.967586,0.971169,0.796671,0.962434,0.509108,...,0.981952,0.743449,0.987742,0.995295,0.461379,0.977762,0.575789,0.673260,0.801421,0.999446

In [8]:
pip install pingouin

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pingouin in c:\users\sahan\appdata\roaming\python\python310\site-packages (0.5.3)
Requirement already satisfied: outdated in c:\users\sahan\appdata\roaming\python\python310\site-packages (from pingouin) (0.2.2)
Requirement already satisfied: seaborn>=0.11 in c:\programdata\anaconda3\lib\site-packages (from pingouin) (0.12.2)
Requirement already satisfied: pandas>=1.0 in c:\programdata\anaconda3\lib\site-packages (from pingouin) (1.5.3)
Requirement already satisfied: tabulate in c:\programdata\anaconda3\lib\site-packages (from pingouin) (0.8.10)
Requirement already satisfied: scipy>=1.7 in c:\programdata\anaconda3\lib\site-packages (from pingouin) (1.10.0)
Requirement already satisfied: numpy>=1.19 in c:\programdata\anaconda3\lib\site-packages (from pingouin) (1.23.5)
Requirement already satisfied: statsmodels>=0.13 in c:\programdata\anaconda3\lib\site-packages (from pingouin) (0.13.5)
Requirement already satisfied: pandas-flavor>=0.2.0 in c:\users\sahan\appdata\roaming\python\python310\site-packages (from pingouin) (0.5.0)
Requirement already satisfied: matplotlib>=3.0.2 in c:\programdata\anaconda3\lib\site-packages (from pingouin) (3.7.0)
Requirement already satisfied: scikit-learn in c:\programdata\anaconda3\lib\site-packages (from pingouin) (1.2.1)
Requirement already satisfied: pillow>=6.2.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.2->pingouin) (9.4.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.2->pingouin) (1.4.4)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.2->pingouin) (1.0.5)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.2->pingouin) (0.11.0)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.2->pingouin) (22.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.2->pingouin) (2.8.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.2->pingouin) (3.0.9)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.2->pingouin) (4.25.0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.0->pingouin) (2022.7)
Requirement already satisfied: xarray in c:\programdata\anaconda3\lib\site-packages (from pandas-flavor>=0.2.0->pingouin) (2022.11.0)
Requirement already satisfied: lazy-loader>=0.1 in c:\users\sahan\appdata\roaming\python\python310\site-packages (from pandas-flavor>=0.2.0->pingouin) (0.2)
Requirement already satisfied: patsy>=0.5.2 in c:\programdata\anaconda3\lib\site-packages (from statsmodels>=0.13->pingouin) (0.5.3)
Requirement already satisfied: littleutils in c:\users\sahan\appdata\roaming\python\python310\site-packages (from outdated->pingouin) (0.2.2)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from outdated->pingouin) (2.28.1)
Requirement already satisfied: setuptools>=44 in c:\programdata\anaconda3\lib\site-packages (from outdated->pingouin) (65.6.3)
Requirement already satisfied: joblib>=1.1.1 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn->pingouin) (1.1.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn->pingouin) (2.2.0)
Requirement already satisfied: six in c:\programdata\anaconda3\lib\site-packages (from patsy>=0.5.2->statsmodels>=0.13->pingouin) (1.16.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests->outdated->pingouin) (1.26.14)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests->outdated->pingouin) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests->outdated->pingouin) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests->outdated->pingouin) (3.4)
Note: you may need to restart the kernel to use updated packages.

In [11]:
import pingouin as pg
print('initial value:\n',pg.cronbach_alpha(data=raw_data),'\n',
     'CoG value:\n',pg.cronbach_alpha(data=raw_data_CoG),'\n',
     'random value:\n',pg.cronbach_alpha(data=raw_data_rnd))

initial value:
 (0.9100377104402944, array([0.895, 0.924]))
 CoG value:
 (0.9164925673689933, array([0.903, 0.929]))
 random value:
 (0.8811133923392956, array([0.861, 0.899]))